# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_time = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb_time.setFont(font)
        self.lb_time.setObjectName("lb_time")
        self.horizontalLayout_2.addWidget(self.lb_time)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lb_time_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lb_time_2.setFont(font)
        self.lb_time_2.setObjectName("lb_time_2")
        self.horizontalLayout_2.addWidget(self.lb_time_2)
        self.lb_status = QtWidgets.QLabel(self.centralwidget)
        self.lb_status.setStyleSheet("min-width:24px;  \n"
"min-height:24px;   \n"
"max-width:24px;  \n"
"max-height:24px;   \n"
"border-radius: 12px;      \n"
"border:1px solid black;  \n"
"background:grey;")
        self.lb_status.setText("")
        self.lb_status.setObjectName("lb_status")
        self.horizontalLayout_2.addWidget(self.lb_status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.te_log = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.te_log.setFont(font)
        self.te_log.setObjectName("te_log")
        self.verticalLayout.addWidget(self.te_log)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.bt_mini = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.bt_mini.setFont(font)
        self.bt_mini.setObjectName("bt_mini")
        self.horizontalLayout.addWidget(self.bt_mini)
        self.bt_stop = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.bt_stop.setFont(font)
        self.bt_stop.setObjectName("bt_stop")
        self.horizontalLayout.addWidget(self.bt_stop)
        self.bt_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        self.bt_start.setFont(font)
        self.bt_start.setObjectName("bt_start")
        self.horizontalLayout.addWidget(self.bt_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.as_config = QtWidgets.QAction(MainWindow)
        self.as_config.setObjectName("as_config")
        self.menu.addAction(self.as_config)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "日志同步工具"))
        self.lb_time.setText(_translate("MainWindow", "运行时间：0:0:0"))
        self.lb_time_2.setText(_translate("MainWindow", "状态："))
        self.bt_mini.setText(_translate("MainWindow", "最小化"))
        self.bt_stop.setText(_translate("MainWindow", "停止"))
        self.bt_start.setText(_translate("MainWindow", "开始"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.as_config.setText(_translate("MainWindow", "配置文件"))
